// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3hnRQiBXBTXzSuPsF0FzWud64IOdyXmg',
    appId: '1:430573416302:android:75fe263e5ddb9090195b7f',
    messagingSenderId: '430573416302',
    projectId: 'orix-febd7',
    storageBucket: 'orix-febd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTqHJnbkA3Hk3XGFfxplM9ZSxMWtjJyFA',
    appId: '1:430573416302:ios:4d66daf305368728195b7f',
    messagingSenderId: '430573416302',
    projectId: 'orix-febd7',
    storageBucket: 'orix-febd7.appspot.com',
    iosClientId: '430573416302-lnhh3o42k0oqpml6tfmoqtpda27al5rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.orix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTqHJnbkA3Hk3XGFfxplM9ZSxMWtjJyFA',
    appId: '1:430573416302:ios:4d66daf305368728195b7f',
    messagingSenderId: '430573416302',
    projectId: 'orix-febd7',
    storageBucket: 'orix-febd7.appspot.com',
    iosClientId: '430573416302-lnhh3o42k0oqpml6tfmoqtpda27al5rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.orix',
  );
}
